export interface Project {
  id: string;
  title: string;
  description: string;
  detailedDescription: string;
  technologies: string[];
  githubUrl: string;
  deployedUrl: string;
  videoUrl?: string;
  image: string;
  category: string;
  subcategory?: string;
  highlights: string[];
  voiceDescription: string;
}

export const allProjects: Project[] = [
  // Business Solution Projects
  {
    id: 'hrm-system',
    title: 'HRM - Human Resource Management System',
    description: 'Complete automated HR management solution with face recognition attendance, payroll automation, and employee portal.',
    detailedDescription: 'A comprehensive Human Resource Management System designed for complete automation of HR operations. The employee portal features daily clock-in/clock-out using facial recognition powered by Machine Learning, location tracking, and time tracking. The system automatically generates payslips based on working hours, manages leave applications, and provides complete employee information access. The HR portal allows managers to create and edit employee profiles, set working hours, manage salaries, and create employee credentials during onboarding. All HR operations are fully automated after initial setup with department-wise analytics.',
    technologies: ['Python', 'Django', 'OpenCV', 'Face Recognition', 'PostgreSQL', 'React', 'Machine Learning', 'REST API'],
    githubUrl: 'https://github.com/shankranand/hrm-system',
    deployedUrl: 'https://gale-reuse-13961800.figma.site/',
    videoUrl: 'https://www.youtube.com/watch?v=hrm-demo',
    image: 'hrm software dashboard',
    category: 'Business Solution Projects',
    highlights: [
      'Face Recognition ML-based attendance system with 98% accuracy',
      'Automated payroll generation based on working hours',
      'Real-time location and time tracking',
      'Complete employee self-service portal',
      'Department-wise analytics and tracking',
      'Automated leave management workflow',
    ],
    voiceDescription: 'Hello! Let me tell you about the HRM system... This is a complete Human Resource Management solution that I built from scratch using Python Django... The coolest feature is the facial recognition based attendance system... where employees just show their face to the camera and boom... they are marked present... The system tracks their location and working hours automatically... And you know what... at the end of the month... payslips are generated automatically based on actual working hours... No manual work needed... The HR team can create employee profiles... set salaries... manage leaves... everything from one dashboard... This project really showcases how automation can transform traditional HR operations... making them super efficient.',
  },
  {
    id: 'crm-system',
    title: 'CRM - Customer Relationship Management',
    description: 'Advanced CRM system for managing customer interactions, sales pipeline, and business relationships.',
    detailedDescription: 'A sophisticated Customer Relationship Management system built to streamline customer interactions and sales processes. Features include comprehensive contact management, deal tracking, sales pipeline visualization, automated follow-up reminders, email integration, customer communication history, analytics dashboards, and reporting tools. The system helps businesses maintain better customer relationships, track sales opportunities, and improve conversion rates through data-driven insights.',
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Chart.js', 'Redis', 'Celery', 'REST API'],
    githubUrl: 'https://github.com/shankranand/crm-system',
    deployedUrl: 'https://www.figma.com/make/fk9kbOVJ5GDLx21EBRLh84/NxtMobility-Full-Stack-ERP-System--Community-?node-id=0-1&p=f&t=iO3SBn2ije2tVFQm-0&fullscreen=1',
    videoUrl: 'https://www.youtube.com/watch?v=crm-demo',
    image: 'crm business software',
    category: 'Business Solution Projects',
    highlights: [
      'Complete sales pipeline management',
      'Automated customer follow-up system',
      'Email and communication integration',
      'Advanced analytics and reporting',
      'Lead scoring and opportunity tracking',
      'Customizable dashboards for insights',
    ],
    voiceDescription: 'So... the CRM system is something I am really proud of... It is basically a complete Customer Relationship Management platform that helps businesses manage all their customer interactions... You know how sales teams struggle to keep track of leads and follow-ups... This system solves that problem completely... It has a beautiful sales pipeline where you can see all your deals in different stages... The automated follow-up reminders ensure no opportunity is missed... Plus... it integrates with email so all communication is tracked automatically... The analytics dashboard shows valuable insights about sales performance and customer behavior... Really helpful for making data driven decisions in business.',
  },
  {
    id: 'erp-system',
    title: 'ERP - Enterprise Resource Planning',
    description: 'Comprehensive ERP solution integrating all business processes including inventory, finance, and operations.',
    detailedDescription: 'A complete Enterprise Resource Planning system that integrates all core business processes into a unified platform. The system manages inventory control, financial accounting, procurement, order management, warehouse operations, reporting and analytics. Features include real-time inventory tracking, automated purchase orders, financial reporting, multi-warehouse support, supplier management, and comprehensive business intelligence dashboards providing end-to-end visibility and control over business operations.',
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Redux', 'Docker', 'Nginx', 'Redis'],
    githubUrl: 'https://github.com/shankranand/erp-system',
    deployedUrl: 'https://www.figma.com/make/fk9kbOVJ5GDLx21EBRLh84/NxtMobility-Full-Stack-ERP-System--Community-?node-id=0-1&p=f&t=iO3SBn2ije2tVFQm-0&fullscreen=1',
    videoUrl: 'https://www.youtube.com/watch?v=erp-demo',
    image: 'erp enterprise system',
    category: 'Business Solution Projects',
    highlights: [
      'Complete business process integration',
      'Real-time inventory management',
      'Financial accounting and reporting',
      'Multi-warehouse operations support',
      'Automated procurement workflows',
      'Business intelligence dashboards',
    ],
    voiceDescription: 'The ERP system is probably the most complex project I have built... It is a complete Enterprise Resource Planning solution that brings together all business operations under one roof... Imagine managing inventory... finances... procurement... warehouse operations... everything from a single platform... That is what this does... The system provides real-time inventory tracking across multiple warehouses... automatically generates purchase orders when stock is low... handles complete financial accounting... and gives you powerful business intelligence dashboards... This level of integration really transforms how businesses operate... making them much more efficient and organized.',
  },

  // Professional Work Projects
  {
    id: 'nxte-mobility-website',
    title: 'NXTE Mobility - Corporate Website',
    description: 'Official corporate website for NXTE Mobility Energy Private Limited showcasing EV solutions.',
    detailedDescription: 'The official corporate website for NXTE Mobility Energy Private Limited, serving as the parent site for the organization. This website showcases the company\'s electric vehicle solutions, services, and vision for sustainable mobility. Features include company information, product showcases, contact forms, responsive design, SEO optimization, and content management integration. Establishes strong online presence as the primary information hub.',
    technologies: ['PHP', 'WordPress', 'MySQL', 'JavaScript', 'CSS3', 'HTML5', 'SEO Tools'],
    githubUrl: 'https://github.com/nxte-mobility/website',
    deployedUrl: 'https://nxtemobility.com/',
    image: 'electric vehicle rental',
    category: 'Professional Work Projects',
    highlights: [
      'Professional corporate website design',
      'Company and services showcase',
      'SEO optimized for visibility',
      'Fully responsive design',
      'Content management system',
      'Integrated contact forms',
    ],
    voiceDescription: 'During my time at NXTE Mobility... I developed their official corporate website... which serves as the main online presence for the company... The website beautifully showcases their electric vehicle solutions and sustainable mobility vision... I focused heavily on SEO optimization to ensure good search engine visibility... made it fully responsive so it looks great on all devices... and integrated a content management system for easy updates... The site includes detailed company information... product showcases... and contact forms for customer inquiries... It really establishes a professional online identity for the company.',
  },
  {
    id: 'kwick-webapp',
    title: 'Kwick - EV Rental Platform with Dashboard',
    description: 'Complete electric vehicle rental platform with web app, mobile app, KYC, and advanced admin dashboard.',
    detailedDescription: 'Kwick is a comprehensive electric vehicle rental platform developed for NXTE Mobility. The platform features user authentication, KYC verification, vehicle booking and management, real-time vehicle tracking, advanced admin dashboard for the Kwick team, payment gateway integration, ride history and analytics. The dashboard provides complete operational oversight including vehicle availability, booking management, revenue tracking, and user management.',
    technologies: ['PHP', 'Laravel', 'MySQL', 'React', 'React Native', 'Payment Gateway', 'Google Maps API', 'REST API'],
    githubUrl: 'https://github.com/nxte-mobility/kwick',
    deployedUrl: 'https://kwick.nxte.in',
    videoUrl: 'https://www.youtube.com/watch?v=kwick-demo',
    image: 'electric vehicle rental',
    category: 'Professional Work Projects',
    highlights: [
      'Complete EV rental platform (Web + Mobile)',
      'Authentication and KYC verification',
      'Real-time vehicle tracking',
      'Advanced admin dashboard with analytics',
      'Integrated payment gateway',
      'Ride history and user management',
    ],
    voiceDescription: 'Kwick is one of my major projects at NXTE Mobility... and I am really excited to talk about it... It is a complete electric vehicle rental platform available both as a web application and a mobile app... Users can register... complete their KYC verification... and start booking electric vehicles within minutes... The platform has real-time vehicle tracking using Google Maps... so you always know where your vehicle is... The best part is the advanced admin dashboard that I built for the Kwick team... It gives them complete control over operations... they can manage vehicle availability... track all bookings... monitor revenue... and handle user accounts... all from one powerful interface... Payment integration makes transactions smooth and secure.',
  },
  {
    id: 'goride-pe',
    title: 'GO RIDE PE - Vehicle Rental WebApp',
    description: 'Professional vehicle rental website with authentication, KYC, and booking management.',
    detailedDescription: 'GO RIDE PE is a vehicle rental website developed for NXTE Mobility, featuring modern UI and comprehensive functionality. Includes user registration and authentication, KYC verification workflow, vehicle browsing and selection, online booking system, booking management dashboard, payment processing, and customer account management providing seamless rental experience.',
    technologies: ['PHP', 'Laravel', 'MySQL', 'JavaScript', 'Bootstrap', 'Payment Integration', 'REST API'],
    githubUrl: 'https://github.com/nxte-mobility/goride-pe',
    deployedUrl: 'https://goridepe.com',
    videoUrl: 'https://www.youtube.com/watch?v=goride-demo',
    image: 'electric vehicle rental',
    category: 'Professional Work Projects',
    highlights: [
      'Modern responsive design',
      'Complete authentication and KYC',
      'Vehicle browsing and selection',
      'Online booking management',
      'Payment gateway integration',
      'Customer dashboard',
    ],
    voiceDescription: 'GO RIDE PE is another professional project I delivered for NXTE Mobility... This is a sleek vehicle rental website with a really modern and intuitive interface... Users can easily browse through available vehicles... check their details... and make online bookings... The platform has complete user authentication and KYC verification to ensure secure transactions... Once booked... customers can manage all their reservations through a personal dashboard... The website features integrated payment processing and works beautifully on all devices thanks to the responsive design... This project really demonstrates my ability to create professional grade web applications for real businesses.',
  },
  {
    id: 'maharatna-ayurveda',
    title: 'Maharatna Ayurveda - Selling Website Platform',
    description: 'E-commerce platform for Ayurvedic products with complete online shopping features.',
    detailedDescription: 'Maharatna Ayurveda is a specialized e-commerce website platform for selling authentic Ayurvedic products. Features include product catalog with detailed descriptions, shopping cart and checkout, secure payment processing, order management system, customer accounts, product categories and filtering, responsive design, and admin panel for inventory management. Platform focuses on showcasing traditional Ayurvedic products with beautiful imagery and informative content.',
    technologies: ['PHP', 'Laravel', 'MySQL', 'JavaScript', 'Bootstrap', 'Payment Gateway', 'REST API'],
    githubUrl: 'https://github.com/shankranand/maharatna-ayurveda',
    deployedUrl: 'https://maharatna-demo.example.com',
    image: 'ayurvedic medicine store',
    category: 'Professional Work Projects',
    highlights: [
      'Specialized Ayurvedic product catalog',
      'Complete e-commerce functionality',
      'Secure checkout and payment',
      'Order tracking system',
      'Product categorization and filtering',
      'Responsive admin panel',
    ],
    voiceDescription: 'Maharatna Ayurveda is a special e-commerce platform I developed for selling authentic Ayurvedic products online... The website has a beautiful product catalog where each item has detailed descriptions and high quality images... Customers can easily browse through different categories... add products to their cart... and complete secure checkout with integrated payment processing... The order management system tracks all purchases... and customers can view their order history through their accounts... I also built an admin panel for the business owner to manage inventory... process orders... and track sales... This project combines e-commerce best practices with the specific needs of traditional Ayurvedic product retail.',
  },

  // Personal Projects - Education
  {
    id: 'lms-platform',
    title: 'LMS - Learning Management System',
    description: 'Complete e-learning platform with course management, video lectures, assessments, and student tracking.',
    detailedDescription: 'A full-featured Learning Management System designed for online education. Includes course creation tools, video lectures integration, assignment submission and grading, quiz and assessment modules, student progress tracking, discussion forums, certificate generation, and analytics for instructors. Students can enroll, watch lectures, submit assignments, take quizzes, and track progress. Instructors have complete control over content and can monitor performance through detailed analytics.',
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Video.js', 'AWS S3', 'WebRTC', 'REST API'],
    githubUrl: 'https://github.com/shankranand/lms-platform',
    deployedUrl: 'https://clink-jungle-76476096.figma.site/',
    videoUrl: 'https://www.youtube.com/watch?v=lms-demo',
    image: 'learning management platform',
    category: 'Personal Projects',
    subcategory: 'Education',
    highlights: [
      'Complete course creation and management',
      'Video lecture integration with tracking',
      'Assignment and quiz system',
      'Student progress analytics',
      'Discussion forums',
      'Automated certificate generation',
    ],
    voiceDescription: 'The LMS platform is my take on modern online education... I built this as a comprehensive Learning Management System... Instructors can create full courses... upload video lectures... create assignments and quizzes... all from an easy to use interface... Students enroll in courses... watch lectures with automatic progress tracking... submit their assignments... and take assessments... The platform has discussion forums for student interaction... which is really important for online learning... Quizzes are graded automatically... and students receive certificates upon course completion... Instructors get detailed analytics showing who is engaging with the content and who needs extra support... It is basically everything you need for professional online education.',
  },

  // Personal Projects - Automation
  {
    id: 'ai-calling-agent',
    title: 'AI Calling Agent - Automation',
    description: 'Advanced N8N automation with AI-powered bulk calling and lead generation agents.',
    detailedDescription: 'An advanced automation system using N8N workflow platform. Includes bulk calling agent for automated customer outreach, AI-powered lead generation agent for qualifying prospects, workflow automation for repetitive tasks, CRM and communication tool integration, automated follow-up sequences, and analytics dashboards. The system significantly reduces manual work and improves efficiency in customer communication and lead management.',
    technologies: ['N8N', 'Python', 'AI APIs', 'Twilio', 'WebHooks', 'PostgreSQL', 'REST API', 'Voice AI'],
    githubUrl: 'https://github.com/shankranand/n8n-automation',
    deployedUrl: 'https://automation-demo.example.com',
    videoUrl: 'https://www.youtube.com/watch?v=n8n-demo',
    image: 'automation workflow system',
    category: 'Personal Projects',
    subcategory: 'Automation',
    highlights: [
      'AI-powered bulk calling agent',
      'Automated lead qualification',
      'Complete workflow automation',
      'CRM integration',
      'Auto follow-up sequences',
      'Analytics dashboard',
    ],
    voiceDescription: 'The AI Calling Agent is cutting edge automation work I did using N8N platform... This system has two main components... First is the bulk calling agent that can make hundreds of automated calls for customer outreach... saving tons of manual effort... Second is an AI powered lead generation agent that actually talks to prospects and qualifies them automatically based on predefined criteria... The entire workflow integrates seamlessly with CRM systems and communication tools... It handles follow up sequences without any human intervention... and provides comprehensive analytics on call performance and lead quality... This kind of automation is the future of sales and marketing... and I am excited to be building these solutions.',
  },

  // Personal Projects - Data Science & AI
  {
    id: 'stock-market-prediction',
    title: 'Stock Market Price Prediction using ML',
    description: 'Machine learning system predicting stock prices using LSTM, technical indicators, and sentiment analysis.',
    detailedDescription: 'Advanced ML project predicting stock market prices using historical data and sophisticated algorithms. Uses LSTM networks, Random Forest, and Gradient Boosting to analyze historical prices, volumes, and indicators. Features include real-time data fetching, technical indicator calculations (RSI, MACD, Moving Averages), sentiment analysis from news, interactive visualization dashboards, and model performance comparison with significant prediction accuracy and confidence intervals.',
    technologies: ['Python', 'TensorFlow', 'Keras', 'Pandas', 'NumPy', 'Scikit-learn', 'LSTM', 'Flask', 'Plotly'],
    githubUrl: 'https://github.com/Sruwat/Stock-Market-Price-Prediction-using-machine-learning',
    deployedUrl: 'https://stock-prediction-demo.example.com',
    videoUrl: 'https://www.youtube.com/watch?v=stock-demo',
    image: 'stock market trading',
    category: 'Personal Projects',
    subcategory: 'Data Science & AI',
    highlights: [
      'LSTM neural networks for time series',
      'Multiple ML models with ensemble',
      'Real-time data and analysis',
      'Technical indicator integration',
      'News sentiment analysis',
      'Interactive dashboards',
    ],
    voiceDescription: 'The Stock Market Prediction project is where I really dive deep into data science and machine learning... This system predicts stock prices using multiple advanced algorithms... including LSTM neural networks which are perfect for time series data... Random Forest... and Gradient Boosting... The system fetches real time data from financial APIs... calculates important technical indicators like RSI... MACD... and moving averages... But here is the cool part... it also does sentiment analysis on financial news to factor in market sentiment... The interactive dashboard lets users visualize predictions... compare different model performances... and see confidence intervals... This project really showcases the power of AI in financial applications.',
  },
  {
    id: 'ai-scan-analysis',
    title: 'AI-Driven  Scan Analysis',
    description: 'Deep learning system for automated medical imaging analysis using CNN for diagnosis assistance.',
    detailedDescription: 'AI-powered medical imaging analysis system assisting healthcare professionals in diagnosis. Uses CNNs and computer vision to analyze X-rays, CT scans, and MRIs. Features include automated abnormality detection, disease classification with confidence scores, region highlighting, comparative analysis, detailed report generation, and hospital system integration. Trained on large datasets achieving high accuracy with explainability features for doctor understanding.',
    technologies: ['Python', 'TensorFlow', 'Keras', 'OpenCV', 'CNN', 'ResNet', 'Flask', 'DICOM', 'NumPy'],
    githubUrl: 'https://github.com/Sruwat/AI-Driven-Scam-Analysis',
    deployedUrl: 'https://www.taylorfrancis.com/chapters/edit/10.1201/9781003593034-137/ai-assisted-scam-detection-notification-system-shabir-ali-shankranand-sarswati-aashish-ranjan',
    videoUrl: 'https://www.youtube.com/watch?v=medical-scan-demo',
    image: 'medical scan ai',
    category: 'Personal Projects',
    subcategory: 'Data Science & AI',
    highlights: [
      'CNN-based image classification',
      'Automated abnormality detection',
      'Disease classification 95%+ accuracy',
      'Region of interest highlighting',
      'Automated report generation',
      'Explainable AI features',
    ],
    voiceDescription: 'AI Driven Medical Scan Analysis is a project I am really passionate about because it can genuinely save lives... This deep learning system helps doctors analyze medical images like X-rays... CT scans... and MRIs... Using Convolutional Neural Networks and advanced architectures like ResNet... it can detect abnormalities and classify diseases with over ninety five percent accuracy... The system highlights specific regions of interest on the scans... generates detailed medical reports... and most importantly... includes explainability features so doctors can understand why the AI made certain decisions... This transparency is crucial in healthcare... The system is trained on large medical imaging datasets and can really assist doctors in making faster and more accurate diagnoses.',
  },
  {
    id: 'ai-trip-planner',
    title: 'AI Trip Planner',
    description: 'Intelligent travel planning system using AI to create personalized itineraries and recommendations.',
    detailedDescription: 'An AI-powered travel planning application that creates personalized trip itineraries based on user preferences, budget, and interests. Features include destination recommendations based on preferences, automated itinerary generation, budget optimization, activity and attraction suggestions, hotel and restaurant recommendations, weather-based planning, map integration for route planning, and collaborative trip planning for groups. Uses machine learning algorithms to learn from user behavior and provide increasingly personalized recommendations.',
    technologies: ['Python', 'Flask', 'OpenAI API', 'React', 'Google Maps API', 'MongoDB', 'Machine Learning', 'REST API'],
    githubUrl: 'https://github.com/shankranand/ai-trip-planner',
    deployedUrl: 'https://trip-planner-demo.example.com',
    videoUrl: 'https://www.youtube.com/watch?v=trip-demo',
    image: 'travel planning app',
    category: 'Personal Projects',
    subcategory: 'Data Science & AI',
    highlights: [
      'AI-powered personalized itineraries',
      'Destination recommendations',
      'Budget optimization',
      'Activity and attraction suggestions',
      'Weather-based planning',
      'Collaborative trip planning',
    ],
    voiceDescription: 'The AI Trip Planner is a fun project that combines AI with travel... This intelligent system helps people plan their perfect vacations... You tell it your preferences... budget... and interests... and it uses AI to create completely personalized itineraries... The system recommends destinations you might love... suggests activities and attractions... finds hotels and restaurants within your budget... and even considers weather patterns for optimal travel dates... It integrates with Google Maps for route planning... and supports collaborative planning if you are traveling with friends or family... The machine learning algorithms learn from user behavior... so recommendations get better over time... It is like having a personal travel agent powered by artificial intelligence.',
  },

  // Personal Projects - Machine Learning
  {
    id: 'face-recognition',
    title: 'Face Recognition Using ML',
    description: 'Advanced face recognition system using Machine Learning for attendance and security applications.',
    detailedDescription: 'Sophisticated Face Recognition system using Machine Learning and Computer Vision. The model uses OpenCV and deep learning to detect and recognize faces with high accuracy. Features include real-time face detection, face encoding and matching, multi-face support, anti-spoofing measures, and integration capabilities. Trained on diverse datasets to ensure accuracy across different lighting conditions and angles.',
    technologies: ['Python', 'OpenCV', 'TensorFlow', 'Keras', 'Face Recognition', 'NumPy', 'scikit-learn', 'Flask'],
    githubUrl: 'https://github.com/shankranand/face-recognition-ml',
    deployedUrl: 'https://face-recognition-demo.example.com',
    videoUrl: 'https://www.youtube.com/watch?v=face-recognition',
    image: 'face recognition technology',
    category: 'Personal Projects',
    subcategory: 'Machine Learning',
    highlights: [
      'Real-time face detection',
      'High accuracy across lighting conditions',
      'Multi-face detection',
      'Anti-spoofing security',
      'Attendance system integration',
      'Speed and accuracy optimized',
    ],
    voiceDescription: 'Face Recognition Using ML is a computer vision project that I am quite proud of... Using OpenCV and TensorFlow... this system can detect and recognize faces in real time with impressive accuracy... It handles multiple faces simultaneously... which is important for group scenarios... The model includes anti spoofing measures to prevent fraudulent access using photos or videos... I trained it on diverse datasets so it works well across different lighting conditions... camera angles... and even with partial face visibility... This is actually the same technology I integrated into the HRM system for automated attendance... but it can also be used for security applications... access control... or any scenario requiring face based identification.',
  },
  {
    id: 'jarvis-voice-assistant',
    title: 'Jarvis - Desktop Voice Assistant',
    description: 'AI-powered desktop voice assistant for hands-free computer control and task automation.',
    detailedDescription: 'Jarvis is an AI-powered desktop voice assistant that enables hands-free computer control and task automation. Features include voice recognition and natural language understanding, system control (opening applications, files, settings), web searching and information retrieval, email and calendar management, music playback control, weather updates and news briefings, custom command creation, and multi-language support. Uses advanced speech recognition and natural language processing to understand commands and context.',
    technologies: ['Python', 'Speech Recognition', 'pyttsx3', 'OpenAI API', 'Natural Language Processing', 'PyAutoGUI', 'Windows API'],
    githubUrl: 'https://github.com/Sruwat/JARVIS-A-desktop-Assistant',
    deployedUrl: '#',
    videoUrl: 'https://www.youtube.com/watch?v=jarvis-demo',
    image: 'voice assistant ai',
    category: 'Personal Projects',
    subcategory: 'Machine Learning',
    highlights: [
      'Voice recognition and NLP',
      'Hands-free computer control',
      'System and application control',
      'Web search and information',
      'Email and calendar integration',
      'Custom command creation',
    ],
    voiceDescription: 'Jarvis is my desktop voice assistant project... inspired by the famous AI from Iron Man... This is a fully functional voice assistant that lets you control your computer hands free... You can ask Jarvis to open applications... search the web... play music... check weather... read your emails... basically anything you would normally do with mouse and keyboard... The system uses advanced speech recognition to understand what you say... and natural language processing to interpret your commands even if they are phrased differently... You can even create custom commands for your specific workflows... It is incredibly useful for productivity... especially when multitasking... Plus it is just really cool to control your computer by voice like in science fiction movies.',
  },

  // Personal Projects - Full Stack Personal
  {
    id: 'bookstore-dashboard',
    title: 'Book Store with Dashboard',
    description: 'Complete online bookstore with inventory management, sales tracking, and admin dashboard.',
    detailedDescription: 'A comprehensive online bookstore application with customer-facing store and powerful admin dashboard. Features include book catalog with search and filtering, shopping cart and secure checkout, order management and tracking, customer accounts and purchase history, admin dashboard for inventory management, sales analytics and reporting, book recommendations, and review system. The dashboard provides complete store oversight including stock management, order processing, and sales insights.',
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Redux', 'Payment Gateway', 'Chart.js', 'REST API'],
    githubUrl: 'https://github.com/shankranand/bookstore',
    deployedUrl: 'https://bookstore-demo.example.com',
    image: 'online bookstore',
    category: 'Personal Projects',
    subcategory: 'Full Stack Personal',
    highlights: [
      'Complete book catalog system',
      'Advanced search and filtering',
      'Shopping cart and checkout',
      'Admin inventory dashboard',
      'Sales analytics and reporting',
      'Customer review system',
    ],
    voiceDescription: 'The Book Store project is a complete e-commerce solution specifically designed for selling books online... On the customer side... people can browse through a comprehensive book catalog... use advanced search and filtering to find what they want... add books to their cart... and complete secure checkout... The site has customer accounts where users can track their orders and view purchase history... But the real power is in the admin dashboard I built... Store owners can manage their entire inventory... add new books... update stock levels... process orders... and view detailed sales analytics... The dashboard shows what is selling well... revenue trends... and customer insights... It is a complete solution for running a modern online bookstore.',
  },
  {
    id: 'ecommerce-dashboard',
    title: 'E-Commerce Platform With Dashboard',
    description: 'Full-featured e-commerce platform with comprehensive admin dashboard for complete store management.',
    detailedDescription: 'A complete e-commerce platform with customer store and powerful admin dashboard. Includes product catalog management, shopping cart and checkout, payment gateway integration, order management system, customer accounts and profiles, admin dashboard with analytics, inventory tracking, sales reporting, promotional tools, and shipping integration. Dashboard provides complete business oversight with real-time data on sales, inventory, customers, and performance metrics.',
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Redux', 'Stripe', 'Redis', 'AWS S3', 'REST API'],
    githubUrl: 'https://github.com/shankranand/ecommerce-platform',
    deployedUrl: 'https://multivendorclient.vercel.app/',
    image: 'ecommerce online store',
    category: 'Personal Projects',
    subcategory: 'Full Stack Personal',
    highlights: [
      'Complete product catalog management',
      'Secure checkout and payments',
      'Comprehensive admin dashboard',
      'Real-time inventory tracking',
      'Sales analytics and reporting',
      'Order and customer management',
    ],
    voiceDescription: 'The E-Commerce Platform is a full featured online store that I built as a personal project to master modern e-commerce development... Customers can browse products... add items to cart... and complete secure checkout with integrated payment processing... The platform has user accounts for order tracking and purchase history... But what sets this apart is the comprehensive admin dashboard... Store owners get a complete business management interface... they can manage products and inventory... process and track orders... view sales analytics with beautiful charts... manage customer accounts... and even run promotional campaigns... The dashboard provides real time insights into business performance... inventory levels... and customer behavior... It is basically everything needed to run a successful online store.',
  },
  {
    id: 'clothing-store-dashboard',
    title: 'Clothing Store Website with Dashboard',
    description: 'Fashion e-commerce website with variant management and comprehensive admin dashboard.',
    detailedDescription: 'A modern clothing e-commerce website with focus on fashion retail and powerful admin dashboard. Features include product galleries with high-quality images, size and color variant management, wishlist functionality, shopping cart and checkout, responsive mobile-optimized design, category and collection browsing, admin dashboard for product management, inventory tracking by size/color, sales analytics, and order processing. Emphasizes visual appeal and user experience with robust backend management.',
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Redux', 'Cloudinary', 'Stripe', 'Chart.js', 'REST API'],
    githubUrl: 'https://github.com/shankranand/clothing-store',
    deployedUrl: 'https://clothing-website-pq6c.vercel.app/',
    image: 'clothing fashion store',
    category: 'Personal Projects',
    subcategory: 'Full Stack Personal',
    highlights: [
      'Beautiful product galleries',
      'Size and color variant management',
      'Mobile-optimized shopping',
      'Comprehensive admin dashboard',
      'Inventory tracking by variants',
      'Sales and order analytics',
    ],
    voiceDescription: 'The Clothing Store Website is specifically designed for fashion retail with a strong focus on visual appeal and variant management... On the customer facing side... there are beautiful product galleries showcasing clothing items... Customers can select size and color variants... add items to wishlist... and enjoy a mobile optimized shopping experience... which is crucial since most fashion shopping happens on mobile devices... The admin dashboard is tailored for clothing retail... allowing store owners to manage products with multiple variants... track inventory by size and color combinations... process orders... and view sales analytics... The product filtering makes it easy for customers to find exactly what they are looking for... This project demonstrates how to build e-commerce solutions for specific retail niches.',
  },
  {
    id: 'multivendor-marketplace',
    title: 'Multi-Vendor Marketplace',
    description: 'Comprehensive marketplace platform enabling multiple vendors to operate virtual shops for customers and shopkeepers.',
    detailedDescription: 'A sophisticated multi-vendor marketplace where multiple sellers can operate virtual shops and sell products. Features include vendor registration and onboarding, individual vendor storefronts, product listing and management, centralized product catalog, commission and payment management, order routing to vendors, vendor analytics dashboards, customer reviews and ratings, admin oversight, and automated vendor payouts. Handles complex marketplace logic including payment splitting between platform and vendors.',
    technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Redux', 'Stripe Connect', 'Redis', 'Celery', 'REST API'],
    githubUrl: 'https://github.com/shankranand/multivendor-marketplace',
    deployedUrl: 'https://multivendorclient.vercel.app/',
    image: 'marketplace vendor platform',
    category: 'Personal Projects',
    subcategory: 'Full Stack Personal',
    highlights: [
      'Multi-vendor architecture',
      'Individual vendor storefronts',
      'Commission and payment splitting',
      'Vendor analytics dashboards',
      'Centralized product catalog',
      'Automated vendor payouts',
    ],
    voiceDescription: 'The Multi Vendor Marketplace is technically one of the most complex projects I have built... This platform allows multiple sellers to create their own virtual shops and sell products to customers... Think of it like creating your own Amazon or Flipkart... Each vendor gets their own storefront where they can list and manage their products... Customers can browse products from all vendors in one centralized catalog... When a purchase is made... the system automatically routes the order to the correct vendor... handles payment splitting between the platform and the vendor... and manages commission calculations... Vendors get their own analytics dashboards to track sales and performance... The platform admin has complete oversight of all vendors and transactions... This kind of marketplace architecture requires handling really complex payment flows... multi-tenancy... and intricate business logic... but it is incredibly powerful for building platforms like this.',
  },
];

// Category definitions for filtering
export const categories = [
  'All Projects',
  'Business Solution Projects',
  'Professional Work Projects',
  'Personal Projects',
];

export const personalSubcategories = [
  'All Personal',
  'Education',
  'Automation',
  'Data Science & AI',
  'Machine Learning',
  'Full Stack Personal',
];
